<script setup>
// 统一图标适配层：业务层只使用 Mnemo 名称，Lucide 实现细节不向外泄漏。
import { computed } from 'vue'
import {
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowLeftRight,
  ArrowUp,
  ArrowUpToLine,
  Camera,
  Captions,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsRight,
  CircleX,
  Cloud,
  CloudDownload,
  Columns2,
  Copy,
  CornerUpLeft,
  Database,
  Download,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  FastForward,
  File,
  FileText,
  Folder,
  FolderInput,
  Globe2,
  Grid2X2,
  HardDrive,
  House,
  Image,
  Info,
  Link,
  List,
  Maximize,
  Minimize,
  Minus,
  Monitor,
  Moon,
  Music,
  PanelTop,
  Pause,
  Pencil,
  PictureInPicture2,
  Play,
  Plus,
  RefreshCw,
  Repeat,
  Rewind,
  RotateCw,
  Search,
  Settings,
  Share2,
  SkipBack,
  SkipForward,
  Square,
  Star,
  Sun,
  Trash2,
  TriangleAlert,
  Undo2,
  Upload,
  Video,
  Volume2,
  VolumeX,
  X,
} from '@lucide/vue'

const props = defineProps({
  name: { type: String, required: true },
  size: { type: [Number, String], default: 16 },
})

// 仅在此处维护 Mnemo 名称与 Lucide 图标的映射，以确保按需导入可被构建器 tree-shake。
const ICONS = Object.freeze({
  columns: Columns2,
  'single-pane': PanelTop,
  folder: Folder,
  file: File,
  video: Video,
  audio: Music,
  image: Image,
  archive: Archive,
  doc: FileText,
  download: Download,
  upload: Upload,
  share: Share2,
  link: Link,
  star: Star,
  trash: Trash2,
  restore: Undo2,
  pencil: Pencil,
  move: FolderInput,
  copy: Copy,
  migrate: ArrowLeftRight,
  search: Search,
  home: House,
  back: ArrowLeft,
  refresh: RefreshCw,
  settings: Settings,
  close: X,
  info: Info,
  alert: TriangleAlert,
  warning: TriangleAlert,
  cloud: Cloud,
  'cloud-down': CloudDownload,
  monitor: Monitor,
  'chevron-right': ChevronRight,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  check: Check,
  grid: Grid2X2,
  list: List,
  external: ExternalLink,
  plus: Plus,
  globe: Globe2,
  pause: Pause,
  play: Play,
  'x-circle': CircleX,
  'up-level': CornerUpLeft,
  'sort-asc': ArrowUp,
  'sort-desc': ArrowDown,
  drive: HardDrive,
  database: Database,
  sun: Sun,
  moon: Moon,
  forward: ChevronsRight,
  rewind: Rewind,
  'fast-forward': FastForward,
  'skip-back': SkipBack,
  'skip-forward': SkipForward,
  repeat: Repeat,
  'rotate-right': RotateCw,
  priority: ArrowUpToLine,
  volume: Volume2,
  'volume-x': VolumeX,
  eye: Eye,
  'eye-off': EyeOff,
  camera: Camera,
  captions: Captions,
  maximize: Maximize,
  minimize: Minimize,
  'window-minimize': Minus,
  'window-maximize': Square,
  'window-restore': Copy,
  'more-horizontal': Ellipsis,
  'picture-in-picture': PictureInPicture2,
  stop: Square,
})

const resolvedName = computed(() => (ICONS[props.name] ? props.name : 'file'))
const icon = computed(() => ICONS[resolvedName.value])
</script>

<template>
  <component
    :is="icon"
    :size="size"
    :stroke-width="1.8"
    aria-hidden="true"
    focusable="false"
    :data-icon-name="resolvedName"
    style="flex-shrink:0;display:inline-block;vertical-align:-2px"
  />
</template>
